services:
  rich.webhook:
    image: rich.webhook
    build:
      context: .
      dockerfile: src/Rich.WebHook/Dockerfile
    ports:
      - 5001:80
      - 5002:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/.aspnethttpsaspnetapp.pfx
#    volumes:
#      - ~/.aspnet/https:/https:ro
