name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print current working directory
        run: cd /home/runner/work/Rich.WebHook && ls -a

      - name: Build and push
        id: docker_build_api
        uses: docker/build-push-action@v6
        with:
          context: /home/runner/work/Rich.WebHook/Rich.WebHook/src/Rich.WebHook
          push: true
          tags: richpeople/webhook:latest

